BEGIN;

DROP TABLE IF EXISTS "contactMe",
"user";

-- -----------------------------------------------------
-- Table "contactMe"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "contactMe" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom" text NOT NULL,
  "mail" text NOT NULL,
  "message" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,--on peut utiliser now() aussi
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "user"
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS "user" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text NOT NULL,
  "password" text NOT NULL,
  "firstname" text NULL,
  "lastname" text NULL,
  "role" VARCHAR(100) NOT NULL DEFAULT 'user',
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- Pour mettre fin à au bloc de transaction et l'exécuter
COMMIT;